extends RefCounted
class_name CatAppearance
## Applies a founder's coat (from cats.json) to the player cat.
##
## The "body" mesh paints its fur AND its eyes into the same shared
## colormap.png texture, sampled via UV on a single mesh surface -- there is
## no separate eye mesh. A flat material override erases both at once, which
## is why an earlier version of this made the eyes vanish. The fix: body
## uses a PRE-BAKED palette-swapped texture per founder (generated by
## tools/generate_cat_textures.py), which recolors only the real fur and eye
## pixel clusters and leaves the rest of the shared atlas untouched. Re-run
## that script after changing any coat color in cats.json.
##
## Tabby stripes are NOT baked into the texture. This model's UV mapping
## mirrors left/right body geometry onto the exact same texture pixels, so
## no texture-space pattern can ever vary color left-to-right (confirmed via
## mesh dump analysis -- see tools/generate_cat_textures.py header for the
## full story). Instead, tabby-patterned founders get a ShaderMaterial
## (founder/tabby_stripes.gdshader) that stripes using the fragment's real
## object-space position, which isn't affected by the broken UV.
##
## Tail and legs are separate, single-color mesh parts with no texture
## detail to preserve, so they still just get a flat accent color.

const TEXTURES_DIR := "res://founder/textures/"
const STRIPE_SHADER := "res://founder/tabby_stripes.gdshader"

const BODY_PATH := "animal-cat2/animal-cat/root/body"
const TAIL_PATH := "animal-cat2/animal-cat/root/body/tail"
const LEG_PATHS := [
	"animal-cat2/animal-cat/root/leg-back-left",
	"animal-cat2/animal-cat/root/leg-back-right",
	"animal-cat2/animal-cat/root/leg-front-left",
	"animal-cat2/animal-cat/root/leg-front-right",
]

static func apply_to_player(player: Node, founder_id: String, coat: Dictionary) -> void:
	if player == null or coat.is_empty():
		return

	var secondary_color := Color(coat.get("secondary_color", coat.get("body_color", "#FFFFFF")))
	var accent_mat := _make_flat_material(secondary_color)

	var body := player.get_node_or_null(BODY_PATH)
	if body:
		body.set_surface_override_material(0, _make_body_material(founder_id, coat))

	var tail := player.get_node_or_null(TAIL_PATH)
	if tail:
		tail.set_surface_override_material(0, accent_mat)

	for leg_path in LEG_PATHS:
		var leg := player.get_node_or_null(leg_path)
		if leg:
			leg.set_surface_override_material(0, accent_mat)

static func _make_body_material(founder_id: String, coat: Dictionary) -> Material:
	var albedo_path := "%scat_%s_albedo.png" % [TEXTURES_DIR, founder_id]
	var pattern: String = coat.get("pattern", "solid")

	if pattern == "tabby":
		var furmask_path := "%scat_%s_furmask.png" % [TEXTURES_DIR, founder_id]
		var shader_mat := ShaderMaterial.new()
		shader_mat.shader = load(STRIPE_SHADER)
		if ResourceLoader.exists(albedo_path):
			shader_mat.set_shader_parameter("albedo_tex", load(albedo_path))
		if ResourceLoader.exists(furmask_path):
			shader_mat.set_shader_parameter("fur_mask_tex", load(furmask_path))
		shader_mat.set_shader_parameter("body_color", Color(coat.get("body_color", "#FFFFFF")))
		shader_mat.set_shader_parameter("secondary_color", Color(coat.get("secondary_color", coat.get("body_color", "#FFFFFF"))))
		shader_mat.set_shader_parameter("stripe_width", 0.15)
		return shader_mat

	var mat := StandardMaterial3D.new()
	if ResourceLoader.exists(albedo_path):
		mat.albedo_color = Color(1, 1, 1)
		mat.albedo_texture = load(albedo_path)
	else:
		# No pre-baked texture for this founder -- e.g. a bonus/DLC founder
		# (Comet) added without running tools/generate_cat_textures.py.
		# Falling back to albedo_color = white here would render solid
		# white (no texture means no fur/eye detail at all), silently
		# ignoring whatever body_color the founder's data actually asks
		# for. Tint the model's own default material instead: wrong shade
		# of "distinct from the baked founders" is a much better failure
		# than "invisible white cat."
		mat.albedo_color = Color(coat.get("body_color", "#FFFFFF"))
	# NOTE: we intentionally do NOT use emission_texture here. Enabling
	# emission on this material -- even with a texture that is verified
	# correct (mostly black, small colored eye patches) -- caused the
	# renderer to wash the ENTIRE body out to solid white, overriding the
	# albedo texture completely (confirmed via screenshot A/B testing:
	# disabling emission_enabled immediately restored the correct fur
	# pattern). Since eye_color is already baked directly into the albedo
	# texture's pupil pixels (see generate_cat_textures.py), each founder's
	# eyes are still distinctly colored without needing a glow effect.
	return mat

static func _make_flat_material(color: Color) -> StandardMaterial3D:
	var mat := StandardMaterial3D.new()
	mat.albedo_color = color
	return mat
